### ISSUE TITLE
Serve app from https://devseed.com/our-forests-tomorrow without /build/ suffix

### ISSUE THREAD

**Issue by batpad** [developmentseed/our-forests-tomorrow#2]
If there's a straightforward way to do this without messing up the folder structure or anything, would be great to have a cleaner URL, without the `/build/` artifact.

There should be some way to configure Github Pages to serve a folder? Am not sure I fully understand this, but something like https://stackoverflow.com/questions/66623128/using-build-as-source-for-a-github-page-for-a-react-app ?

cc @kamicut @nerik 

Feel free to close as "wontfix" if this requires effort beyond some configuration in GH pages.

**Comment by kamicut** [comment]
@nerik I'm not sure, but it seems that the Github Actions that are being used to build the site are using a Jekyll build? Not sure why that's the case because we're not using Jekyll. We would have to create our own actions for build and publish and follow https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by nerik** [comment]
@batpad I can definitely fix that.
@kamicut Github Pages does not require Jekyll anymore, it can just serve static assets. Enabling GH pages on a project will automatically create a [deploy action](https://github.com/developmentseed/our-forests-tomorrow/actions/workflows/pages/pages-build-deployment).

We also could use another solution than GH pages, what would be the DS way? Netlify?

**Comment by batpad** [comment]
> We also could use another solution than GH pages, what would be the DS way? Netlify?

I think GH pages is fine? I think we do host quite a few things just using gh-pages, and unless @kamicut has a strong opinion here, I'd vote for "if its not broken, let's not fix it" on this one.

**Comment by nerik** [comment]
Fixed!
